// Demo dataset matching the real column schema.
// Used until the user loads an actual xlsx file.
// Gaps (empty strings) are intentional — they exercise the "missing" UI.

window.DEMO_ROWS = [
  {
    product_id: "P001",
    product_name: "Thailand Climate Change Knowledge Portal",
    delivery_format: "Web Platform",
    service_type: "Dashboard; Report",
    owner: "ONEP",
    developer: "TGO",
    geographic_scope: "Thailand",
    description: "National portal aggregating climate projections, sectoral risk briefs and NAP progress for Thailand.",
    group_of_use_case: "Climate Information; Decision Support",
    use_case: "climate projection; policy briefing",
    sectors: "Water; Agriculture; Public Health",
    url: "https://climate.onep.go.th",
    "GFCS Pillar Related": "Climate Services Information System; User Interface Platform"
  },
  {
    product_id: "P002",
    product_name: "ThaiWater Risk Map",
    delivery_format: "Web Platform",
    service_type: "Map/GIS",
    owner: "HII",
    developer: "HII",
    geographic_scope: "Thailand",
    description: "Flood and drought risk mapping at sub-district resolution.",
    group_of_use_case: "Risk & Vulnerability Assessment",
    use_case: "flood risk mapping; drought monitoring",
    sectors: "Water; Agriculture",
    url: "https://www.thaiwater.net",
    "GFCS Pillar Related": "Observations & Monitoring; Research & Modeling"
  },
  {
    product_id: "P003",
    product_name: "RIMES Climate Outlook",
    delivery_format: "Web Platform",
    service_type: "Dashboard; Report",
    owner: "RIMES",
    developer: "RIMES",
    geographic_scope: "Regional",
    description: "Sub-seasonal to seasonal climate outlooks for Asia-Pacific member states.",
    group_of_use_case: "Climate Information",
    use_case: "seasonal forecast; early warning",
    sectors: "Agriculture; Disaster Risk Management",
    url: "https://www.rimes.int",
    "GFCS Pillar Related": "Research & Modeling; Climate Services Information System"
  },
  {
    product_id: "P004",
    product_name: "ND-GAIN Country Index",
    delivery_format: "Web Platform",
    service_type: "Dashboard",
    owner: "University of Notre Dame",
    developer: "",
    geographic_scope: "Global",
    description: "Country-level vulnerability and readiness scores for climate adaptation.",
    group_of_use_case: "Risk & Vulnerability Assessment",
    use_case: "country benchmarking",
    sectors: "",
    url: "https://gain.nd.edu",
    "GFCS Pillar Related": ""
  },
  {
    product_id: "P005",
    product_name: "NAP Tracker TH",
    delivery_format: "Web Platform",
    service_type: "Dashboard",
    owner: "ONEP",
    developer: "",
    geographic_scope: "Thailand",
    description: "",
    group_of_use_case: "Decision Support",
    use_case: "NAP progress tracking",
    sectors: "Water; Agriculture; Tourism; Public Health; Natural Resource Management; Human Settlement",
    url: "",
    "GFCS Pillar Related": "User Interface Platform"
  },
  {
    product_id: "P006",
    product_name: "AgWeather TH",
    delivery_format: "Mobile App",
    service_type: "Dashboard",
    owner: "TMD",
    developer: "TMD",
    geographic_scope: "Thailand",
    description: "Farmer-facing weather advisories tied to crop calendars.",
    group_of_use_case: "Climate Information",
    use_case: "weather advisory; agro-advisory",
    sectors: "Agriculture",
    url: "",
    "GFCS Pillar Related": "User Interface Platform; Capacity Development"
  },
  {
    product_id: "P007",
    product_name: "Climate Risk Profile — Mekong",
    delivery_format: "Web Platform",
    service_type: "Report",
    owner: "USAID",
    developer: "Chemonics",
    geographic_scope: "Regional",
    description: "PDF library of country and basin climate risk profiles.",
    group_of_use_case: "Risk & Vulnerability Assessment; Climate Information",
    use_case: "country risk profile",
    sectors: "",
    url: "https://www.climatelinks.org",
    "GFCS Pillar Related": ""
  },
  {
    product_id: "P008",
    product_name: "Copernicus Climate Data Store",
    delivery_format: "Web Platform",
    service_type: "Data Portal; Map/GIS",
    owner: "ECMWF",
    developer: "ECMWF",
    geographic_scope: "Global",
    description: "Open access to reanalysis, seasonal forecasts and climate projections.",
    group_of_use_case: "Climate Information",
    use_case: "climate projection; reanalysis access",
    sectors: "Water; Agriculture; Energy",
    url: "https://cds.climate.copernicus.eu",
    "GFCS Pillar Related": "Observations & Monitoring; Research & Modeling; Climate Services Information System"
  },
  {
    product_id: "P009",
    product_name: "Coastal Vulnerability Viewer TH",
    delivery_format: "Web Platform",
    service_type: "Map/GIS",
    owner: "DMCR",
    developer: "",
    geographic_scope: "Thailand",
    description: "Shoreline change and coastal hazard exposure for Thai provinces.",
    group_of_use_case: "Risk & Vulnerability Assessment",
    use_case: "coastal erosion mapping",
    sectors: "Natural Resource Management; Tourism",
    url: "",
    "GFCS Pillar Related": "Observations & Monitoring"
  },
  {
    product_id: "P010",
    product_name: "DEWETRA",
    delivery_format: "Web Platform",
    service_type: "Dashboard; Map/GIS",
    owner: "CIMA Foundation",
    developer: "CIMA Foundation",
    geographic_scope: "Global",
    description: "Real-time multi-hazard monitoring and early-warning platform.",
    group_of_use_case: "Decision Support; Risk & Vulnerability Assessment",
    use_case: "early warning; multi-hazard monitoring",
    sectors: "Disaster Risk Management",
    url: "https://www.cimafoundation.org/dewetra",
    "GFCS Pillar Related": "Climate Services Information System; User Interface Platform"
  },
  {
    product_id: "P011",
    product_name: "Health & Heat TH",
    delivery_format: "Mobile App",
    service_type: "",
    owner: "MOPH",
    developer: "",
    geographic_scope: "Thailand",
    description: "",
    group_of_use_case: "Climate Information",
    use_case: "heat advisory",
    sectors: "Public Health",
    url: "",
    "GFCS Pillar Related": ""
  },
  {
    product_id: "P012",
    product_name: "ASEAN Climate Resilience Dashboard",
    delivery_format: "Web Platform",
    service_type: "Dashboard",
    owner: "ASEAN Secretariat",
    developer: "",
    geographic_scope: "Regional",
    description: "Indicators of climate resilience progress across ASEAN member states.",
    group_of_use_case: "Decision Support",
    use_case: "policy benchmarking; case studies",
    sectors: "",
    url: "https://asean.org",
    "GFCS Pillar Related": "User Interface Platform"
  }
];
